import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <img alt='' src={"header.png"} />
        <div className={styles.headertext}>
          <h1 >The Purposeful<br /> Pursuit</h1>
          <p >Lorem iopasd  daskdasd k</p>
        </div>
      </div>

      <div className={styles.container}>

      </div>
    </>
  )
}
